spring:
    datasource:
        url: 'jdbc:sqlserver://localhost:1433;databaseName=db_isay'
        username: 'db_isay'
        password: 'Smp*202204'
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    application:
        name: test
logging:
    level:
        web: debug
    config: 