cart:
  #  points-sink-url: http://localhost:8081
  points-sink-url: http://localhost:8081/ok
  #  points-sink-url: http://localhost:8081/timeout
  #  points-sink-url: http://localhost:8081/retry
  coffees: 'Sumatra;Breakfast Blend;Blend of the Day'
###
spring:
  config:
    active:
      on-profile: default
  data:
    mongodb:
      uri: mongodb://localhost:27017/cart
####
#spring:
#  config:
#    active:
#      on-cloud-platform: kubernetes
#  data:
#    mongodb:
#      uri: mongodb://${CART_MONGODB_SERVICE_HOST}:${CART_MONGODB_PORT}}/cart
